### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by S0raWasTaken** [LOOHP/Limbo#18]
### Details:
- Java 8 (Also tested with Java 11)
- Crashes after sending *"Loading packet id mappings from mapping.json ..."*
- Version 0.4.4-ALPHA

### Error message:
```diff
Exception in thread "main"
- [15:59:58 Error ] java.lang.ClassNotFoundException: com.loohp.limbo.server.packets.PacketPlayOutShowPlayerSkins
- [15:59:58 Error]        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
- [15:59:58 Error]        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
- [15:59:58 Error]        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
- [15:59:58 Error]        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
- [15:59:58 Error]        at java.lang.Class.forName0(Native Method)
- [15:59:58 Error]        at java.lang.Class.forName(Class.java:264)
- [15:59:58 Error]        at com.loohp.limbo.Limbo.<init>(Limbo.java:253)
- [15:59:58 Error]        at com.loohp.limbo.Limbo.main(Limbo.java:102)

**Comment by LOOHP** [comment]
Try deleting the internal data folder and then restart
