### ISSUE TITLE
Exception when starting

### ISSUE THREAD

**Issue by TheMainGeek** [LOOHP/Limbo#32]
When I start the Limbo plugin, I get an index out of bounds error:
[20:32:42 Error]java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[20:32:42 Error]        at com.loohp.limbo.file.ServerProperties.<init>(ServerProperties.java:84)
[20:32:42 Error]        at com.loohp.limbo.Limbo.<init>(Limbo.java:168)
[20:32:42 Error]        at com.loohp.limbo.Limbo.main(Limbo.java:99)
How to fix?

**Comment by TheMainGeek** [comment]
Nevermind I fixed it :)
