### ISSUE TITLE
JPremium Support

### ISSUE THREAD

**Issue by MrGoraj** [LOOHP/Limbo#62]
This project would be ideal for plugins like JPremium that use limbo servers.

But unfortunately, when I tested the possibility of running this plugin on the latest build 1.19.3, it displayed such errors in the console:

```
[20:31:16 Error]java.lang.reflect.InvocationTargetException
[20:31:16 Error]        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[20:31:16 Error]        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[20:31:16 Error]        at com.loohp.limbo.Limbo.<init>(Limbo.java:334)
[20:31:16 Error]        at com.loohp.limbo.Limbo.main(Limbo.java:133)
[20:31:16 Error]Caused by: java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
[20:31:16 Error]        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[20:31:16 Error]        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
[20:31:16 Error]        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[20:31:16 Error]        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
[20:31:16 Error]        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
[20:31:16 Error]        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
[20:31:16 Error]        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
[20:31:16 Error]        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
[20:31:16 Error]        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[20:31:16 Error]        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[20:31:16 Error]        at java.base/java.lang.Class.forName0(Native Method)
[20:31:16 Error]        at java.base/java.lang.Class.forName(Class.java:495)
[20:31:16 Error]        at java.base/java.lang.Class.forName(Class.java:474)
[20:31:16 Error]        at com.loohp.limbo.plugins.PluginManager.loadPlugins(PluginManager.java:78)
[20:31:16 Error]        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[20:31:16 Error]        ... 3 more
[20:31:16 Error]Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
[20:31:16 Error]        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[20:31:16 Error]        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[20:31:16 Error]        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[20:31:16 Error]        ... 18 more
```

**Comment by byquanton** [comment]
JPremium is a Bukkit Plugin. On Limbo, you can only use plugin compiled against its api.

**Comment by CarmJos** [comment]
Limbo is **not implemented** any Bukkit/Spigot/BungeeCord/Velocity API,
and it's **completely not compatible** and will **never compatible** with any plugins of them.

You need to use the provided API to develop your own plugins.
