### ISSUE TITLE
world schematic not loading

### ISSUE THREAD

**Issue by modpotato** [LOOHP/Limbo#69]
[22:03:06 Info] Unable to load world compulsion.schem!
[22:03:06 Error]java.lang.NullPointerException: Cannot invoke "net.querz.nbt.tag.CompoundTag.keySet()" because "palette" is null
[22:03:06 Error]        at com.loohp.limbo.world.Schematic.toWorld(Schematic.java:42)
[22:03:06 Error]        at com.loohp.limbo.Limbo.loadDefaultWorld(Limbo.java:405)
[22:03:06 Error]        at com.loohp.limbo.Limbo.<init>(Limbo.java:296)
[22:03:06 Error]        at com.loohp.limbo.Limbo.main(Limbo.java:132)

schematic was created with worldedit bukkit on 1.20.6
https://tmpfiles.org/dl/7604091/compulsion.schem

**Comment by msinfo32github** [comment]
Encountering the same problem here - did you find a solution?

**Comment by msinfo32github** [comment]
I have solved this problem. The plugin appears to accept WorldEdit's sponge.2 format. 

This is saved from using the `/schematic` command.

I used this command, and then uploaded the outputted file into the root directory of the server.

`/schematic save -f filename sponge.2`

Replace `filename` with your filename such as `world.schem`
