### ISSUE TITLE
Issue With Starting Limbo

### ISSUE THREAD

**Issue by ItzMonkeyMax** [LOOHP/Limbo#7]
Hey there! 

I am experiencing some difficulty with starting my server, I am using this startup command:
java -jar Limbo.jar --nogui

And I get this error on trying to start it.

:/home/container$ java -jar Limbo.jar --nogui
[20:14:07 Info] Loading Limbo Version 0.3.7-ALPHA on Minecraft 1.16.4
Exception in thread "main" [20:14:07 Error]java.lang.NumberFormatException: null
[20:14:07 Error]        at java.lang.Integer.parseInt(Integer.java:542)
[20:14:07 Error]        at java.lang.Integer.parseInt(Integer.java:615)
[20:14:07 Error]        at com.loohp.limbo.File.ServerProperties.<init>(ServerProperties.java:45)
[20:14:07 Error]        at com.loohp.limbo.Limbo.<init>(Limbo.java:164)
[20:14:07 Error]        at com.loohp.limbo.Limbo.main(Limbo.java:101)

Any help would be apreciated!

Thank you, 
Max

**Comment by LOOHP** [comment]
Seems like there are some problems with the server.properties file, can you show me that file?

**Comment by ItzMonkeyMax** [comment]
Yes!

Here you go:

server-ip=0.0.0.0
enable-query=true
server-port=2464

**Comment by ItzMonkeyMax** [comment]
Issue was to do with Server.Properties. If anyone has this issue, replace your server.properties with:

https://www.github.com/LOOHP/Limbo/tree/master/src%2Fserver.properties
